hpcgarage/spatter

include/sgbuf.h, src/main.c, src/parse-args.c, src/sgbuf.c
Preliminary support for the ms1 pattern. No accompanying scripts are provided. To use it, specify three command line parameters. 
--ms1-flag
--ms1-run=<# contiguous elements>
--ms1-gap=<# elements between blocks>
The only works for Gather and Scatter kernels. I feel the combined SG should probably be deprecated.
=> Add Mostly Stride 1 Pattern

src/sgbuf.c
This adds support to trace_indices() to map the indices / addresses in the idx[] array from sparse pages that could be far apart from eachother with lage gaps into a group of consecutive pages that are dense.  The associated addresses / indices in idx[] are then re-written to reference the new, dense pages.
=> Add sparse page to dense page translation support to trace_indices().

cuda/cuda-backend.c, cuda/cuda-backend.h, cuda/my_kernel.cu, include/sgbuf.h, opencl/ocl-backend.c, opencl/ocl-backend.h, src/main.c, src/parse-args.c
This finishes removing the dense block parameter aka `B` from the code. It also removes a number of other command line arguments that have become unused in our testing and simplifies the logic in parse-args accordingly. 
Edit: This also adds a short argument for --trace-file , -t.
=> Cleanup Command-line Arguments

src/mt19937-64.c, src/sgbuf.c
This doesn't do much but speed up the init / fill of random data using pthreads and a thread-safe version of the MT rand gen code you already have. The other init slowdown does appear to be in the processing of the input config file's data. I can make that faster as well in another commit if you'd like.
=> Add thread-local state to mt rnd gen, parallelize random data fill.

src/mt19937-64.c, src/sgbuf.c
This PR has a couple of fixups for things which I never hit as a problem yet, but seemed like they could be improved anyway. -- Also this shows an experimental option, disabled with "#if 0" in "sgbuf.c" which would discard the first delta from each G/S pattern entry; this is the delta between SIMD instructions. Enabling this option (skipping the first delta) makes the memory used substantially more consistent as well as often smaller. I, subjectively, have not seen a large change in reported kernel performance between the case of this being enabled vs. not.
=> Adding skip option (delta between G/S instructions), sundry fixups.

src/sp_alloc.c
I did not implement detection of missing `aligned_alloc` or where to set `USE_POSIX_MEMALIGN`.
I am averse to CMake so it's probably better if you do this anyways.
Signed-off-by: Hammond, Jeff R <jeff.r.hammond@intel.com>
=> add posix_memalign workaround for missing aligned_alloc

CMakeLists.txt, configure/configure_omp_intel, include/parse-args.h, include/sgtime.h, src/parse-args.c, src/trace-util.c
Some headers and a source define were needed for compilation with icc.
=> Add headers to fix icc compilation errors

.github/workflows/build.yml
Adds Github Action that makes `configure_serial_gnu` to make sure that new pull requests to the `master` branch do not break the code.
=> Add Github Actions for build testing

README.md
Added instructions for initializing `git submodule` to fix the following error:
```
The source directory
/spatter/external/argtable3
does not contain a CMakeLists.txt file.
```
=> Add `git submodule` instructions

LICENSE, include/parse-args.h, src/main.c, src/parse-args.c
Changes:
1. Dynamically allocated arrays in parse-args in addition to increased values for STRING_SIZE and MAX_PATTERN_LEN to handle larger patterns identified from our traces.
2. Added a re-mapping routine in main.c to re-map huge memory offsets from our patterns (i.e. heap accesses) to fit within the array allocated by Spatter.
3. The -q flag now tale values from 0-3 to vary the amount of output printed (to limit the printing of entire long g/s patterns)
4. Updated LICENSE file
=> LANL: Longer Patterns and Re-Mapping of Huge Memory Offsets

CMakeLists.txt, configure/configure_cuda
CMake with `module load cuda` and ./configure/configure_cuda not easily configurable to set appropriate paths
CUDA CMake updates:
- update to findpackage(CudaToolkit)
- include_directories to include CUDA headers
- target_link_libraries updated to `CUDA::cudart`
- argument passed to `configure/configure_cuda` to specify the compute capability (changed to `CMAKE_CUDA_ARCHITECTURES`) to provide more flexibility
Am now able to easily build on A100 and H100 internally
=> CUDA CMake updates: Needed for a few internal runs that Galen and I are doing

.github/workflows/build.yml
The tests don't run for the `main` branch because we didn't update the `build.yml` file. This fixes that.
=> Change workflow to run for main instead of master

src/main.c
Comparison of negative `int` with unsigned `size_t` caused `time = 0` for all kernels. 
[Reference](https://stackoverflow.com/a/3642067/14837560)
=> Cast size_t nruns to int for comparison (Fixes time = 0 bug)

CMakeLists.txt
There was a typo in line 66 of `CMakeLists.txt`.
=> Fix typo and indentation

README.md, src/cuda/my_kernel.cu, src/main.c, src/parse-args.c, tests/CMakeLists.txt, tests/multilevel.c, tests/standard_ms1_suite.c, tests/standard_uniform_suite.c
Changes:
- Remove some extra output
- Stop users from running patterns larger than 1024 on GPU (this constraint should be removed in the future)
- Some GPU tests would fail silently. This has been fixed
- GPU tests which were failing silently because of bad pattern lengths have been updated.
Persisting issues:
- GPUs only support power of 2 pattern sizes between 8 and 1024. The Laplacian test has an irregular size and should not be run on GPU. (Test 28)
- When using the CUDA backend, we should run `standard_suite_gpu` instead of `standard_suite_cpu`. (Test 34)
@agustin-vaca Could you take a look at these two issues and push an update to this PR if you're able to solve them?
@JDTruj2018 Could you run this and see if it works ok with your GPU tests?
=> Fix issues with CUDA testing

src/include/parse-args.h, src/parse-args.c
Simply increasing these constants to account for some of the larger LANL patterns.
=> Increase MAX_PATTERN_LEN and STRING_SIZE constants

src/cuda/cuda-backend.h, src/cuda/my_kernel.cu, src/main.c
- Moved CUDA kernels in PR #165 into Spatter which can handle longer patterns
- Gather, Scatter, ScatterGather, MultiGather, MultiScatter
- Removed error messages for too long patterns unless a random seed is used
#closes 154
=> Long GPU Patterns implementation

src/parse-args.c
Fixes issue where illegal UTF-8 characters were appearing in the run configuration section of Spatter output.
=> Fix illegal UTF-8 characters in output

README.md, src/parse-args.c
Added a flag (`-u`) to enable automatic strong scaling rather than relying on utilizing the `--pattern-size` flag to appropriately truncate the pattern.
The advantage being that each MPI rank gets a portion of the pattern, rather than an identical chunk of the first `n` items in a pattern, which is the behavior of the `--pattern-size` flag.
For example:
```
mpirun -n 2 ./spatter -p0,1,2,3,4,5,6,7,8 -u
Strong Scaling Enabled
Running Spatter version 1.0
Compiler: GNU ver. 9.4.0
Compiler Location: /projects/opt/centos8/x86_64/gcc/9.4.0/bin/gcc
Backend: Aggregate Results? YES
Run Configurations
[ {'name':'CUSTOM', 'kernel':'Gather', 'pattern':[0,1,2,3], 'pattern_gather':[], 'pattern_scatter':[], 'delta':8, 'deltas_gather':[], 'deltas_scatter':[], 'length':1024, 'agg':10, 'wrap':1, } ]
config …
```
=> Strong scaling by splitting pattern amongst ranks

src/cuda/my_kernel.cu
Unnecessary checks on (j < pattern_length) in the CUDA kernels, since j is calculated from `j = total_id % pattern_length`.
The only check necessary in all CUDA kernels is `if (i < count)` since `i = total_id / pattern_length` can be larger than `count`.
=> Remove unnecessary bounds checks in cuda kernels

src/main.c
I separated this into 2 commits
The first commit adds MPI Barriers prior to each kernel call. This changes the barriers to be at the run granularity rather than at the config granularity since the default number of runs is 10 and we probably want to make sure each rank is synced up before calling the actual kernel. This was done for each kernel of all 3 backends
The second commit is the suggested load-balance fix which adds an MPI Barrier prior to the call to sg_get_time_ms after each kernel has finished (for the Serial and OpenMP backends). The result will be that the measured time corresponds to the slowest rank. This time is captured for each run (the default number of runs is set to 10) and then the minimum runtime (maximum BW) is reported by each rank.
=> Mpi barriers

src/Spatter/Configuration.cc
This PR updates the OpenMP kernels to address an issue with the gather kernel and aligns them closer to their v1.1 implementations. As mentioned in #189, there is still a gap in performance between the current scatter, multiscatter, and sg OpenMP kernels on certain platforms.
- Remove duplicate gather operation in the gather OpenMP kernel
- Align the OpenMP kernels closer to the OpenMP kernels in v1.1
- Use the `dense_perthread` buffers in the scatter and multiscatter OpenMP kernels
- Performance alignment of the scatter, multiscatter, and sg kernels on certain platforms (Cascade Lake, Ice Lake, Sandy Bridge...)
=> Update OpenMP Kernels

src/Spatter/Configuration.cc, src/Spatter/Configuration.hh, src/Spatter/Input.hh, src/Spatter/JSONParser.cc, src/Spatter/JSONParser.hh, tests/parse_run_config_suite_cpu.cc
This PR adds the `--dense-buffers` command-line option to enable the use of multiple dense buffers in the OpenMP kernels. The OpenMP kernels will now default to using a single dense buffer.
- Added `--dense-buffers` command-line option
- Updated OpenMP kernels to use either `dense_perthread` or `dense` buffers
- Added tests for the `--dense-buffers` option
- Closes #191
=> Make OpenMP dense buffers a command line option

src/CMakeLists.txt, src/main.cc
This PR updates Spatter to print the current version during runs, as set by `project()` in the top-level CMakeLists.txt file.
- Spatter now prints version 2.0.0 instead of version 1.1
- Closes #224
=> Print Current Version of Spatter

src/Spatter/Input.hh
This PR initializes the source and destination buffers with random data in parallel for the OpenMP backend.
- Initializes sparse, sparse_gather, sparse_scatter, dense, and dense_perthread buffers in parallel
- Uses thread-safe rand_r() instead of rand() for buffer initialization
- Closes #216
=> Initialize Buffers in Parallel

standard-suite/basic-tests/gpu-stream.json, tests/CMakeLists.txt, tests/standard_suite_stream_cpu.cc, tests/standard_suite_stream_gpu.cc, tests/standard_suite_traces_cpu.cc, tests/standard_suite_traces_gpu.cc, tests/standard_suite_uniform_cpu.cc, tests/standard_suite_uniform_gpu.cc
This PR splits the standard suite test into separate tests for STREAM-like, uniform stride, and application trace patterns; similar to the [GettingStarted.ipynb](https://github.com/hpcgarage/spatter/blob/spatter-devel/notebooks/GettingStarted.ipynb) notebook. Additionally, this PR updates the patterns in the GPU STREAM-like test to use the default count for all kernels.
- standard_suite_cpu and standard_suite_gpu split into separate tests
- gpu-stream.json now uses same count for all patterns
- No additional TODOs for this PR
=> Split Standard Suite Tests
